"""
Venue registry.

Every venue declares HOW its listings can be read, not just where they live.
Strategies, in order of reliability:

  jsonld   - page embeds schema.org Event objects in <script type="application/ld+json">.
             Self-describing, survives redesigns. Best case.
  ics      - venue publishes an iCalendar feed. Even better than jsonld when it exists.
  rss      - RSS/Atom feed with dates in the items.
  custom   - a hand-written adapter in scrape/adapters/. Fragile; use only when the
             venue is worth the maintenance.
  link     - no machine-readable listings. We do not scrape; the calendar links out.

`enabled: False` means "registered but not yet proven". Run probe.py to find out which
of the jsonld/ics guesses actually pay off, then flip them on. Do not trust this file's
guesses — trust the probe.
"""

# category ids must match the front-end: dance, classical, opera, talks,
# broadway, art, global, jazz, houses, access, islands
Venue = dict


def V(id, name, cat, url, strategy="jsonld", enabled=True, **kw):
    return dict(id=id, name=name, cat=cat, url=url, strategy=strategy,
                enabled=enabled, **kw)


VENUES = [
    # ---------------- dance ----------------
    V("nycballet", "New York City Ballet", "dance",
      "https://www.nycballet.com/season-and-tickets/calendar/",
      exclude=["talk", "conversation", "class", "workshop", "seminar", "lecture"]),
    V("joyce", "The Joyce Theater", "dance", "https://www.joyce.org/performances"),
    V("ailey", "Alvin Ailey", "dance", "https://www.alvinailey.org/performances"),
    V("abt", "American Ballet Theatre", "dance", "https://www.abt.org/performances/"),
    V("dth", "Dance Theatre of Harlem", "dance",
      "https://www.dancetheatreofharlem.org/performance/"),
    V("citycenter", "New York City Center", "dance",
      "https://www.nycitycenter.org/whats-on/"),
    V("danspace", "Danspace Project", "dance",
      "https://danspaceproject.org/calendar/"),

    # ---------------- classical ----------------
    V("nyphil", "New York Philharmonic", "classical",
      "https://nyphil.org/concerts-tickets/calendar/"),
    V("carnegie", "Carnegie Hall", "classical",
      "https://www.carnegiehall.org/Calendar"),
    V("townhall", "The Town Hall", "classical", "https://thetownhall.org/calendar/"),
    V("frick", "The Frick Collection", "classical", "https://www.frick.org/events"),
    V("metlivearts", "Met Live Arts", "classical",
      "https://www.metmuseum.org/events"),
    V("morgan", "The Morgan Library", "classical",
      "https://www.themorgan.org/programs"),
    V("92ny_music", "92NY", "classical", "https://www.92ny.org/concerts"),
    V("bargemusic", "Bargemusic", "classical", "https://www.bargemusic.org/"),
    V("sawdust", "National Sawdust", "classical",
      "https://nationalsawdust.org/calendar/"),
    V("stlukes", "Church of St. Luke in the Fields", "classical",
      "https://stlukeinthefields.org/music/"),
    V("corpus", "Corpus Christi — Music Before 1800", "classical",
      "https://www.corpuschristinyc.org/music-before-1800"),
    V("stthomas", "St. Thomas Church Fifth Avenue", "classical",
      "https://www.saintthomaschurch.org/music/concerts/"),
    V("stjohn", "Cathedral of St. John the Divine", "classical",
      "https://www.stjohndivine.org/calendar"),
    V("trinity", "Trinity Church Wall Street", "classical",
      "https://trinitywallstreet.org/music-arts"),
    V("stignatius", "St. Ignatius Loyola — SMSS", "classical",
      "https://www.smssconcerts.org/"),
    V("stbarts", "St. Bartholomew's", "classical", "https://stbarts.org/music/"),
    V("emanuel", "Temple Emanu-El — Streicker", "classical",
      "https://www.emanuelnyc.org/streicker-center/"),
    V("czech", "Bohemian National Hall", "classical",
      "https://www.czechcenter.com/", enabled=False),

    # ---------------- opera ----------------
    V("prototype", "PROTOTYPE Festival", "opera", "https://prototypefestival.org/"),
    V("bmp", "Beth Morrison Projects", "opera",
      "https://www.bethmorrisonprojects.org/"),
    V("operalafayette", "Opera Lafayette", "opera", "https://operalafayette.org/"),
    V("onsite", "On Site Opera", "opera", "https://www.osopera.org/"),
    V("nycopera", "New York City Opera", "opera", "https://nycopera.com/"),
    V("bam", "BAM", "opera", "https://www.bam.org/"),
    V("armory", "Park Avenue Armory", "opera",
      "https://www.armoryonpark.org/programs_events/calendar"),

    # ---------------- talks & theater ----------------
    V("92ny_talks", "92NY — Talks", "talks", "https://www.92ny.org/talks"),
    V("nypl", "LIVE from NYPL", "talks",
      "https://www.nypl.org/events/programs/live"),
    V("greenespace", "The Greene Space", "talks", "https://www.thegreenespace.org/"),
    V("public", "The Public Theater", "talks",
      "https://publictheater.org/whats-on/"),
    V("joespub", "Joe's Pub", "talks", "https://publictheater.org/joes-pub/"),
    V("symphonyspace", "Symphony Space", "talks",
      "https://www.symphonyspace.org/events"),
    V("strand", "The Strand", "talks", "https://www.strandbooks.com/events"),
    V("newschool", "The New School", "talks", "https://event.newschool.edu/"),
    V("shed", "The Shed", "talks", "https://theshed.org/program"),
    V("pacnyc", "Perelman Performing Arts Center", "talks",
      "https://pacnyc.org/whats-on/"),
    V("stanns", "St. Ann's Warehouse", "talks", "https://stannswarehouse.org/"),
    V("cherrylane", "Cherry Lane Theatre", "talks",
      "https://www.cherrylanetheatre.org/", enabled=False),
    V("kitchen", "The Kitchen", "talks", "https://thekitchen.org/"),
    V("roulette", "Roulette", "talks", "https://roulette.org/calendar/"),
    V("signature", "Signature Theatre", "talks",
      "https://www.signaturetheatre.org/"),
    V("atlantic", "Atlantic Theater Company", "talks", "https://atlantictheater.org/"),
    V("csc", "Classic Stage Company", "talks", "https://www.classicstage.org/"),
    V("tfana", "Theatre for a New Audience", "talks", "https://www.tfana.org/"),
    V("centerforfiction", "The Center for Fiction", "talks",
      "https://centerforfiction.org/events/"),
    V("mcnally", "McNally Jackson", "talks",
      "https://www.mcnallyjackson.com/events"),
    V("bam_magic", "Books Are Magic", "talks",
      "https://www.booksaremagic.net/events"),
    V("albertine", "Albertine", "talks", "https://www.albertine.com/events/"),
    V("cfr", "Council on Foreign Relations", "talks", "https://www.cfr.org/events"),
    V("asiasociety", "Asia Society", "talks",
      "https://asiasociety.org/new-york/events"),
    V("nyhistory", "New-York Historical", "talks",
      "https://www.nyhistory.org/programs"),
    V("roosevelthouse", "Roosevelt House", "talks",
      "https://roosevelthouse.hunter.cuny.edu/events/"),
    V("worldleaders", "Columbia World Leaders Forum", "talks",
      "https://worldleaders.columbia.edu/events"),
    V("sipa", "Columbia SIPA", "talks", "https://www.sipa.columbia.edu/events"),
    V("carnegiecouncil", "Carnegie Council", "talks",
      "https://www.carnegiecouncil.org/events"),
    V("japansociety", "Japan Society", "talks", "https://japansociety.org/events/"),
    V("fiaf", "FIAF", "talks", "https://fiaf.org/events/"),
    V("italianacademy", "Italian Academy, Columbia", "talks",
      "https://italianacademy.columbia.edu/events"),
    V("amnh", "American Museum of Natural History", "talks",
      "https://www.amnh.org/calendar"),
    V("nyas", "New York Academy of Sciences", "talks",
      "https://www.nyas.org/events/"),
    V("simons", "Simons Foundation", "talks",
      "https://www.simonsfoundation.org/events/"),
    V("pioneerworks", "Pioneer Works", "talks",
      "https://pioneerworks.org/calendar"),
    V("pen", "PEN America", "talks", "https://pen.org/events/"),
    V("poetrysociety", "Poetry Society of America", "talks",
      "https://poetrysociety.org/events", enabled=False),
    V("poetshouse", "Poets House", "talks", "https://poetshouse.org/", enabled=False),
    V("nybooks", "New York Review of Books", "talks",
      "https://www.nybooks.com/events/", enabled=False),
    V("parisreview", "The Paris Review", "talks",
      "https://www.theparisreview.org/events", enabled=False),
    V("newyorker", "The New Yorker Festival", "talks",
      "https://festival.newyorker.com/", enabled=False),

    # ---------------- broadway ----------------
    V("broadway", "Broadway (all houses)", "broadway",
      "https://www.broadway.org/shows", strategy="custom", adapter="broadway"),

    # ---------------- art: new york ----------------
    V("met", "The Metropolitan Museum of Art", "art",
      "https://www.metmuseum.org/exhibitions"),
    V("moma", "MoMA", "art", "https://www.moma.org/calendar/exhibitions"),
    V("guggenheim", "Guggenheim", "art", "https://www.guggenheim.org/exhibitions"),
    V("neue", "Neue Galerie", "art", "https://www.neuegalerie.org/exhibitions"),
    V("frick_ex", "The Frick Collection", "art", "https://www.frick.org/exhibitions"),
    V("morgan_ex", "The Morgan Library", "art",
      "https://www.themorgan.org/exhibitions"),
    V("whitney", "Whitney Museum", "art", "https://whitney.org/exhibitions"),
    V("brooklynmuseum", "Brooklyn Museum", "art",
      "https://www.brooklynmuseum.org/exhibitions"),
    V("cooperhewitt", "Cooper Hewitt", "art",
      "https://www.cooperhewitt.org/events/current-exhibitions/"),
    V("jewishmuseum", "The Jewish Museum", "art",
      "https://thejewishmuseum.org/exhibitions"),
    V("asiasociety_museum", "Asia Society Museum", "art",
      "https://asiasociety.org/new-york/exhibitions"),
    V("noguchi", "Noguchi Museum", "art", "https://www.noguchi.org/exhibitions/"),
    V("hispanic", "Hispanic Society", "art", "https://hispanicsociety.org/"),
    V("drawingcenter", "The Drawing Center", "art",
      "https://drawingcenter.org/exhibitions"),
    V("posterhouse", "Poster House", "art", "https://posterhouse.org/exhibitions/"),
    V("cima", "Center for Italian Modern Art", "art",
      "https://www.italianmodernart.org/", enabled=False),
    V("roerich", "Nicholas Roerich Museum", "art", "https://www.roerich.org/",
      enabled=False),
    V("mmuseumm", "Mmuseumm", "art", "https://mmuseumm.com/", enabled=False),
    V("rubin", "Rubin Museum", "art", "https://rubinmuseum.org/", enabled=False),

    # ---------------- art: global ----------------
    V("gagosian", "Gagosian", "global", "https://gagosian.com/exhibitions/"),
    V("hauserwirth", "Hauser & Wirth", "global",
      "https://www.hauserwirth.com/exhibitions/"),
    V("zwirner", "David Zwirner", "global",
      "https://www.davidzwirner.com/exhibitions"),
    V("pace", "Pace", "global", "https://www.pacegallery.com/exhibitions/"),
    V("whitecube", "White Cube", "global",
      "https://www.whitecube.com/gallery-exhibitions"),
    V("ropac", "Thaddaeus Ropac", "global", "https://ropac.net/exhibitions/"),
    V("perrotin", "Perrotin", "global", "https://www.perrotin.com/exhibitions"),
    V("lisson", "Lisson Gallery", "global",
      "https://www.lissongallery.com/exhibitions"),
    V("gladstone", "Gladstone", "global",
      "https://www.gladstonegallery.com/exhibitions"),
    V("mariangoodman", "Marian Goodman", "global",
      "https://www.mariangoodman.com/exhibitions/"),
    V("acquavella", "Acquavella", "global",
      "https://www.acquavellagalleries.com/exhibitions"),
    V("hufkens", "Xavier Hufkens", "global",
      "https://www.xavierhufkens.com/exhibitions"),
    V("lehmannmaupin", "Lehmann Maupin", "global",
      "https://www.lehmannmaupin.com/exhibitions"),
    V("victoriamiro", "Victoria Miro", "global",
      "https://www.victoria-miro.com/exhibitions/"),
    V("sadiecoles", "Sadie Coles HQ", "global",
      "https://www.sadiecoles.com/exhibitions/"),
    V("kurimanzutto", "kurimanzutto", "global",
      "https://www.kurimanzutto.com/en/exhibitions"),
    V("nga", "National Gallery of Art", "global",
      "https://www.nga.gov/exhibitions.html"),
    V("hirshhorn", "Hirshhorn", "global", "https://hirshhorn.si.edu/exhibitions/"),
    V("louvre", "Musée du Louvre", "global", "https://www.louvre.fr/en/what-s-on"),
    V("tate", "Tate", "global", "https://www.tate.org.uk/whats-on"),
    V("nationalgallery_uk", "The National Gallery, London", "global",
      "https://www.nationalgallery.org.uk/exhibitions"),
    V("britishmuseum", "The British Museum", "global",
      "https://www.britishmuseum.org/exhibitions"),
    V("pompidou", "Centre Pompidou", "global",
      "https://www.centrepompidou.fr/en/program"),
    V("prado", "Museo del Prado", "global",
      "https://www.museodelprado.es/en/whats-on"),
    V("reinasofia", "Museo Reina Sofía", "global",
      "https://www.museoreinasofia.es/en/exhibitions"),
    V("rijksmuseum", "Rijksmuseum", "global",
      "https://www.rijksmuseum.nl/en/whats-on"),
    V("flv", "Fondation Louis Vuitton", "global",
      "https://www.fondationlouisvuitton.fr/en"),
    V("artic", "Art Institute of Chicago", "global",
      "https://www.artic.edu/exhibitions"),

    # ---------------- jazz & cabaret ----------------
    # Confirmed WordPress + WooCommerce, custom `event` post type; artist name is the
    # post title. No schema.org markup, so the generic jsonld pass finds nothing here.
    V("vanguard", "Village Vanguard", "jazz", "https://villagevanguard.com/",
      strategy="custom", adapter="wordpress", wp="posts", wp_type="event",
      default_time="20:00"),
    V("bluenote", "Blue Note", "jazz", "https://www.bluenotejazz.com/nyc/"),
    V("smalls", "Smalls", "jazz", "https://www.smallslive.com/", strategy="custom", adapter="wordpress"),
    V("mezzrow", "Mezzrow", "jazz", "https://www.mezzrow.com/", strategy="custom", adapter="wordpress"),
    V("dizzys", "Dizzy's Club", "jazz", "https://www.jazz.org/dizzys/"),
    V("smoke", "Smoke Jazz Club", "jazz", "https://www.smokejazz.com/", strategy="custom", adapter="wordpress"),
    V("birdland", "Birdland", "jazz", "https://www.birdlandjazz.com/"),
    V("jazzgallery", "The Jazz Gallery", "jazz", "https://jazzgallery.org/calendar/", strategy="custom", adapter="wordpress"),
    V("nines", "The Nines", "jazz", "https://www.thenines.nyc/", enabled=False),
    V("lunatico", "Bar LunÀtico", "jazz", "https://www.barlunatico.com/", strategy="custom", adapter="wordpress"),
    V("54below", "54 Below", "jazz", "https://54below.org/"),
    V("greenroom42", "The Green Room 42", "jazz", "https://thegreenroom42.com/"),
    V("carlyle", "Café Carlyle", "jazz",
      "https://www.rosewoodhotels.com/en/the-carlyle-new-york/dining/cafe-carlyle",
      enabled=False),

    # ---------------- historic houses ----------------
    V("merchants", "Merchant's House Museum", "houses",
      "https://merchantshouse.org/events/"),
    V("morrisjumel", "Morris-Jumel Mansion", "houses",
      "https://www.morrisjumel.org/events"),
    V("vancortlandt", "Van Cortlandt House", "houses", "https://vchmuseum.org/"),
    V("mvhm", "Mount Vernon Hotel Museum", "houses", "https://www.mvhm.org/"),
    V("bartowpell", "Bartow-Pell Mansion", "houses",
      "https://www.bartowpellmansionmuseum.org/"),
    V("aliceausten", "Alice Austen House", "houses", "https://aliceausten.org/"),
    V("kingmanor", "King Manor", "houses", "https://www.kingmanor.org/"),
    V("bownehouse", "Bowne House", "houses", "https://www.bownehouse.org/",
      enabled=False),
    V("dyckman", "Dyckman Farmhouse", "houses", "https://dyckmanfarmhouse.org/"),
    V("gracie", "Gracie Mansion", "houses",
      "https://www.nyc.gov/site/graciemansion/index.page", strategy="link"),

    # ---------------- special access ----------------
    V("greenwood", "Green-Wood Cemetery", "access",
      "https://www.green-wood.com/events/"),
    V("woodlawn", "Woodlawn Cemetery", "access",
      "https://www.woodlawn.org/events/"),
    V("ohny", "Open House New York", "access", "https://ohny.org/"),
    V("untapped", "Untapped New York", "access",
      "https://www.untappedcities.com/tours/"),
    V("marblecemetery", "New York Marble Cemetery", "access",
      "https://www.marblecemetery.org/", strategy="link"),
    V("nycmc", "New York City Marble Cemetery", "access",
      "https://nycmc.org/", strategy="link"),

    # ---------------- islands ----------------
    V("govisland", "Governors Island", "islands",
      "https://www.govisland.com/things-to-do/events"),
    V("ellis", "Ellis Island Hospital Hard Hat Tour", "islands",
      "https://www.statueellisisland.org/", strategy="link"),
    V("hartisland", "Hart Island", "islands",
      "https://www.nyc.gov/site/hart/index.page", strategy="link"),
    V("northbrother", "North Brother Island", "islands",
      "https://www.nycgovparks.org/parks/north-brother-island", strategy="link"),
]

BY_ID = {v["id"]: v for v in VENUES}


def scrapable():
    return [v for v in VENUES
            if v["enabled"] and v["strategy"] in ("jsonld", "ics", "rss", "custom")]
